package com.xa.dao;

import com.xa.pojo.Menu;
import java.math.BigDecimal;

public interface MenuMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MENU
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(BigDecimal menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MENU
     *
     * @mbggenerated
     */
    int insert(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MENU
     *
     * @mbggenerated
     */
    int insertSelective(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MENU
     *
     * @mbggenerated
     */
    Menu selectByPrimaryKey(BigDecimal menuId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MENU
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Menu record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MENU
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Menu record);
}