package com.xa.dao;

import com.xa.pojo.Userinfo;
import com.xa.pojo.UserinfoExample;
import java.math.BigDecimal;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface UserinfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERINFO
     *
     * @mbggenerated
     */
    int countByExample(UserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERINFO
     *
     * @mbggenerated
     */
    int deleteByExample(UserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERINFO
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(BigDecimal userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERINFO
     *
     * @mbggenerated
     */
    int insert(Userinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERINFO
     *
     * @mbggenerated
     */
    int insertSelective(Userinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERINFO
     *
     * @mbggenerated
     */
    List<Userinfo> selectByExample(UserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERINFO
     *
     * @mbggenerated
     */
    Userinfo selectByPrimaryKey(BigDecimal userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERINFO
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") Userinfo record, @Param("example") UserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERINFO
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") Userinfo record, @Param("example") UserinfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERINFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(Userinfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table USERINFO
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(Userinfo record);
}