package com.xa.pojo;

import java.math.BigDecimal;

public class Userinfo {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERINFO.USER_ID
     *
     * @mbggenerated
     */
    private BigDecimal userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERINFO.USER_NAME
     *
     * @mbggenerated
     */
    private String userName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERINFO.USER_PAS
     *
     * @mbggenerated
     */
    private String userPas;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column USERINFO.USER_EMAIL
     *
     * @mbggenerated
     */
    private String userEmail;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERINFO.USER_ID
     *
     * @return the value of USERINFO.USER_ID
     *
     * @mbggenerated
     */
    public BigDecimal getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERINFO.USER_ID
     *
     * @param userId the value for USERINFO.USER_ID
     *
     * @mbggenerated
     */
    public void setUserId(BigDecimal userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERINFO.USER_NAME
     *
     * @return the value of USERINFO.USER_NAME
     *
     * @mbggenerated
     */
    public String getUserName() {
        return userName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERINFO.USER_NAME
     *
     * @param userName the value for USERINFO.USER_NAME
     *
     * @mbggenerated
     */
    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERINFO.USER_PAS
     *
     * @return the value of USERINFO.USER_PAS
     *
     * @mbggenerated
     */
    public String getUserPas() {
        return userPas;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERINFO.USER_PAS
     *
     * @param userPas the value for USERINFO.USER_PAS
     *
     * @mbggenerated
     */
    public void setUserPas(String userPas) {
        this.userPas = userPas == null ? null : userPas.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column USERINFO.USER_EMAIL
     *
     * @return the value of USERINFO.USER_EMAIL
     *
     * @mbggenerated
     */
    public String getUserEmail() {
        return userEmail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column USERINFO.USER_EMAIL
     *
     * @param userEmail the value for USERINFO.USER_EMAIL
     *
     * @mbggenerated
     */
    public void setUserEmail(String userEmail) {
        this.userEmail = userEmail == null ? null : userEmail.trim();
    }
}